/*
 * This source file was generated by the Gradle 'init' task
 */
package org.simplon;

import java.io.File;

import org.apache.catalina.Context;
import org.apache.catalina.LifecycleException;
import org.apache.catalina.WebResourceRoot;
import org.apache.catalina.startup.Tomcat;
import org.apache.catalina.webresources.DirResourceSet;
import org.apache.catalina.webresources.StandardRoot;

public class App {
    public static void main(String[] args) {
        // Instanciation server
        Tomcat tomcat = new Tomcat();

        // Definit le port du serveur
        tomcat.setPort(8080);

        // Création d'un connector, pas besoin de le stocker en variable
        tomcat.getConnector();

        File publicFolder = new File("src/main/webapp/");

        if (!publicFolder.exists()) {
            // mkdirs va créer tous les fichiers qui n'existent pas
            publicFolder.mkdirs();
        }

        // Contexte server web
        Context ctx = tomcat.addWebapp("", publicFolder.getAbsolutePath());

        ctx.addWelcomeFile("login");

        //Lire les classes Java avec l'annotation @WebServlet automatiquement
        File classesFolder = new File("build/classes/java/main");

        WebResourceRoot resources = new StandardRoot(ctx);
        
        resources.addPreResources(new DirResourceSet(
            resources,
            "/WEB-INF/classes",
            classesFolder.getAbsolutePath(),
            "/"
        ));
        ctx.setResources(resources);

        // Démarrage du server
        try {
            tomcat.start();
        } catch (LifecycleException e) {
            e.printStackTrace();
        }

        // On bloque le main tant que le server est disponible
        tomcat.getServer().await();

    }
}
